# docker-compose.yml

version: '3.8'

services:
  cache:
    image: varnish
    ports:
      - "80:80"
    volumes:
      - "./varnish/config.vcl:/etc/varnish/default.vcl"

  web:
    image: varn
    build: .
    command: uvicorn app.plot:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"